version: '3'
services:
  floating-database:
    build: .
    image: floating-database:latest
    command: 1234 -s 8080 -i redis
    links: [redis]
    ports: [8080:8080]
  redis:
    image: redis:latest
